-- Extracted from the remaining available PDFs in doc/.
-- Sources: Learn & Talk I, Chapter 12 Lessons 109-111 and Chapter 13 Lessons 114-118.
-- Source PDFs for Lessons 112 and 113 were unavailable during this import.
-- The target table is created by aliyun_daily_spoken_dialogue_buying_clothes.sql.
-- Re-running this file updates only the lesson_code/item_order pairs below.

SET NAMES utf8mb4;
START TRANSACTION;

-- Lesson 109 · Energy (doc/117592_4653_Energy.pdf)
INSERT INTO `daily_spoken_dialogue_item` (
    `lesson_code`, `chapter_title`, `lesson_title`, `lesson_order`,
    `section_code`, `section_title`, `section_order`, `item_type`, `item_order`,
    `speaker`, `item_title`, `english_text`, `chinese_text`, `pronunciation`,
    `explanation`, `examples`, `keywords`, `is_published`
) VALUES
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'vocabulary', '核心词汇', 1, 'vocabulary', 1, NULL, 'sustainable', 'sustainable', '可持续的', '/səˈsteɪnəbl/', 'involving the use of natural products and energy in a way that does not harm the environment', 'This car uses sustainable energy.', 'sustainable, energy', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'vocabulary', '核心词汇', 1, 'vocabulary', 2, NULL, 'alternative', 'alternative', '可替代的', '/ɔːlˈtɜːrnətɪv/', 'a thing that you can choose to do or have out of two or more possibilities', 'Wind power is an alternative energy source.', 'alternative, energy', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'vocabulary', '核心词汇', 1, 'vocabulary', 3, NULL, 'recycle', 'recycle', '回收再用', '/ˌriːˈsaɪkl/', 'to treat things that have already been used so that they can be used again', 'It is meaningful to do garbage recycling.', 'recycle, energy', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'vocabulary', '核心词汇', 1, 'vocabulary', 4, NULL, 'pervade', 'pervade', '渗透', '/pərˈveɪd/', 'to spread through and be noticeable in every part of something', 'Electricity pervades every aspect of our lives.', 'pervade, energy', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'vocabulary', '核心词汇', 1, 'vocabulary', 5, NULL, 'properly', 'properly', '正确地；合适地', '/ˈprɑːpərli/', 'in a way that is correct and appropriate', 'The car is still not working properly.', 'properly, energy', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'dialogue', '示范对话', 2, 'dialogue', 101, 'Jack', NULL, 'Guess what! I recently bought an electric car.', '你猜怎么着！我最近买了一辆电动汽车。', NULL, NULL, NULL, 'electric car, energy', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'dialogue', '示范对话', 2, 'dialogue', 102, 'Mary', NULL, 'But I heard that the electric vehicle technology is not mature enough.', '但我听说电动汽车技术还不够成熟。', NULL, NULL, NULL, 'electric vehicle, technology', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'dialogue', '示范对话', 2, 'dialogue', 103, 'Jack', NULL, 'That''s true, but I want to buy a car using sustainable energy. And electricity is the best alternative energy out there in my opinion.', '没错，但我想买一辆使用可持续能源的车。我认为电力是目前最好的替代能源。', NULL, NULL, NULL, 'sustainable, alternative energy', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'dialogue', '示范对话', 2, 'dialogue', 104, 'Mary', NULL, 'You''re right. I can''t afford a battery electric vehicle, but I always do garbage recycling and use public transportation.', '你说得对。我买不起纯电动汽车，但我总会进行垃圾回收并乘坐公共交通。', NULL, NULL, NULL, 'garbage recycling, public transportation', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'dialogue', '示范对话', 2, 'dialogue', 105, 'Jack', NULL, 'You make your own contribution to energy saving. That''s great of you.', '你在为节约能源作出自己的贡献。你真棒。', NULL, NULL, NULL, 'contribution, energy saving', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'dialogue', '示范对话', 2, 'dialogue', 106, 'Mary', NULL, 'Energy touches every aspect of modern civilization and pervades our daily lives. We should make use of energy properly.', '能源触及现代文明的方方面面，并渗透在我们的日常生活中。我们应该合理利用能源。', NULL, NULL, NULL, 'pervade, properly, energy', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'practice', '情景补全对话', 3, 'practice', 201, 'A', NULL, 'Do you have any tips for saving energy?', '你有什么节约能源的建议吗？', NULL, '根据课件提示补全。', NULL, 'energy saving, practice', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'practice', '情景补全对话', 3, 'practice', 202, 'B', NULL, 'I do garbage recycling and always take public transport.', '我会进行垃圾回收，并总是乘坐公共交通。', NULL, NULL, NULL, 'recycling, public transport', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'practice', '情景补全对话', 3, 'practice', 203, 'A', NULL, 'That''s great of you. I plan to buy a battery electric vehicle.', '你真棒。我计划买一辆纯电动汽车。', NULL, NULL, NULL, 'battery electric vehicle', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'practice', '情景补全对话', 3, 'practice', 204, 'B', NULL, 'Wonderful. Electricity is good alternative energy.', '太好了。电力是一种很好的替代能源。', NULL, NULL, NULL, 'alternative energy', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'practice', '情景补全对话', 3, 'practice', 205, 'A', NULL, 'That''s what I think too. Energy pervades every aspect of our lives. We should make use of it properly.', '我也是这么想的。能源渗透在生活的方方面面，我们应该合理利用它。', NULL, NULL, NULL, 'pervade, properly', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'discussion', '开口讨论', 4, 'discussion', 301, NULL, NULL, 'Can you list some forms of energy? Which do you use more frequently, and what do you use it for?', '你能列举一些能源形式吗？你最常用哪一种？用来做什么？', NULL, '可谈 electricity、gas、natural gas、coal、fuel、solar energy，以及热水、开车、烹饪、照明等用途。', NULL, 'energy, discussion', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'discussion', '开口讨论', 4, 'discussion', 302, NULL, NULL, 'Do you try to save energy in daily life? What measures do you take?', '你会在日常生活中节约能源吗？采取哪些措施？', NULL, '可谈乘公共交通、垃圾回收、离开时关灯等。', NULL, 'energy saving, discussion', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'review', '复习表达', 5, 'review', 401, NULL, 'Key expressions', 'I recently bought an electric car/a battery electric vehicle. That''s true, but I want to buy a car using sustainable energy. Electricity is the best alternative energy. I always do garbage recycling and use public transportation.', '复习：sustainable / alternative / recycle / pervade / properly。', NULL, NULL, NULL, 'review, energy', 1),
    ('energy', 'Chapter 12 · Environment', 'Lesson 109 · Energy', 109, 'extra', '拓展学习', 6, 'extra', 501, NULL, 'Forms of Energy', 'solar energy; tidal energy; nuclear energy; geothermal energy', '能源形式：太阳能；潮汐能；核能；地热能。', NULL, '课后拓展词汇。', NULL, 'solar energy, tidal energy, nuclear energy, geothermal energy', 1)
ON DUPLICATE KEY UPDATE
    `chapter_title` = VALUES(`chapter_title`), `lesson_title` = VALUES(`lesson_title`), `lesson_order` = VALUES(`lesson_order`),
    `section_code` = VALUES(`section_code`), `section_title` = VALUES(`section_title`), `section_order` = VALUES(`section_order`),
    `item_type` = VALUES(`item_type`), `speaker` = VALUES(`speaker`), `item_title` = VALUES(`item_title`),
    `english_text` = VALUES(`english_text`), `chinese_text` = VALUES(`chinese_text`), `pronunciation` = VALUES(`pronunciation`),
    `explanation` = VALUES(`explanation`), `examples` = VALUES(`examples`), `keywords` = VALUES(`keywords`),
    `is_published` = VALUES(`is_published`);

-- Lesson 117 · Artificial Intelligence (doc/118393_4654_Artificial Intelligence.pdf)
INSERT INTO `daily_spoken_dialogue_item` (
    `lesson_code`, `chapter_title`, `lesson_title`, `lesson_order`,
    `section_code`, `section_title`, `section_order`, `item_type`, `item_order`,
    `speaker`, `item_title`, `english_text`, `chinese_text`, `pronunciation`,
    `explanation`, `examples`, `keywords`, `is_published`
) VALUES
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'vocabulary', '核心词汇', 1, 'vocabulary', 1, NULL, 'artificial intelligence', 'artificial intelligence', '人工智能', '/ˌɑːrtɪfɪʃl ɪnˈtelɪdʒəns/', 'an area of study concerned with making computers copy intelligent human behavior; the full spelling of AI', 'Many countries are working on artificial intelligence.', 'artificial intelligence, AI', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'vocabulary', '核心词汇', 1, 'vocabulary', 2, NULL, 'sophisticated', 'sophisticated', '精密的；复杂的；高级的', '/səˈfɪstɪkeɪtɪd/', 'clever and complicated in the way a machine or system works or is presented', 'Medical techniques are becoming more sophisticated all the time.', 'sophisticated, AI', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'vocabulary', '核心词汇', 1, 'vocabulary', 3, NULL, 'advanced', 'advanced', '先进的', '/ədˈvænst/', 'having the most modern and recently developed ideas or methods', 'China has advanced technology.', 'advanced, AI', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'vocabulary', '核心词汇', 1, 'vocabulary', 4, NULL, 'complex', 'complex', '复杂的', '/kəmˈpleks/', 'made of many connected parts; difficult to understand', 'The watch has a complex design.', 'complex, AI', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'vocabulary', '核心词汇', 1, 'vocabulary', 5, NULL, 'unmanned', 'unmanned', '无人的', '/ˌʌnˈmænd/', 'describing a machine, vehicle, place, or activity that does not need a person to control or operate it', 'Unmanned vehicles have many problems that need to be solved.', 'unmanned, AI', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'dialogue', '示范对话', 2, 'dialogue', 101, 'Jack', NULL, 'How do you think about artificial intelligence (AI)?', '你怎么看人工智能（AI）？', NULL, NULL, NULL, 'artificial intelligence, AI', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'dialogue', '示范对话', 2, 'dialogue', 102, 'Mary', NULL, 'I think it''s the most sophisticated and advanced technology field at present. Many countries are working on it.', '我认为它目前是最精密、最先进的技术领域，许多国家都在研究它。', NULL, NULL, NULL, 'sophisticated, advanced, AI', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'dialogue', '示范对话', 2, 'dialogue', 103, 'Jack', NULL, 'That''s true, but there is a debate about whether we should build something that is smarter than us.', '没错，但人们在争论是否应该制造比我们更聪明的东西。', NULL, NULL, NULL, 'AI, debate', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'dialogue', '示范对话', 2, 'dialogue', 104, 'Mary', NULL, 'This situation is a little bit complex. On one hand, AI will help humans build a better life in many aspects, such as personal assistants in cellphones and unmanned vehicles. On the other hand, AI can be a threat when a weapon is out of control due to technology malfunction.', '这种情况有点复杂。一方面，AI 会在许多方面帮助人类创造更好的生活，如手机个人助理和无人驾驶车辆；另一方面，当武器因技术故障失控时，AI 也可能构成威胁。', NULL, NULL, NULL, 'complex, unmanned, technology malfunction', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'dialogue', '示范对话', 2, 'dialogue', 105, 'Jack', NULL, 'Seems like technology advancement can be both beneficial and harmful.', '技术进步似乎既可能有益，也可能有害。', NULL, NULL, NULL, 'technology advancement', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'dialogue', '示范对话', 2, 'dialogue', 106, 'Mary', NULL, 'I guess it depends on whether humans can make use of the technology properly.', '我想这取决于人类能否正确地利用技术。', NULL, NULL, NULL, 'technology, properly', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'practice', '情景补全对话', 3, 'practice', 201, 'A', NULL, 'Look, my phone has a personal assistant in it.', '看，我的手机里有个人助理。', NULL, '根据课件提示补全。', NULL, 'personal assistant, AI', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'practice', '情景补全对话', 3, 'practice', 202, 'B', NULL, 'It''s the work of artificial intelligence.', '这是人工智能的成果。', NULL, NULL, NULL, 'artificial intelligence', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'practice', '情景补全对话', 3, 'practice', 203, 'A', NULL, 'AI? It sounds like a sophisticated and advanced technology. What can AI do?', 'AI？听起来像一种精密而先进的技术。AI 能做什么？', NULL, NULL, NULL, 'sophisticated, advanced', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'practice', '情景补全对话', 3, 'practice', 204, 'B', NULL, 'For example, it can free people from some labor work, like driving a car or working in a factory.', '例如，它可以把人们从一些劳动工作中解放出来，如开车或在工厂工作。', NULL, NULL, NULL, 'AI, labor work', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'practice', '情景补全对话', 3, 'practice', 205, 'A', NULL, 'An unmanned car? It sounds like something in a movie. I love this technology.', '无人驾驶汽车？听起来像电影里的东西。我喜欢这项技术。', NULL, NULL, NULL, 'unmanned car, AI', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'discussion', '开口讨论', 4, 'discussion', 301, NULL, NULL, 'Explain artificial intelligence in your own words. Name some work that uses it.', '用自己的话解释人工智能，并列举一些使用它的工作或产品。', NULL, '可谈计算机模仿人类思维和行为；无人车、无人机、机器人、手机个人助理等。', NULL, 'artificial intelligence, discussion', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'discussion', '开口讨论', 4, 'discussion', 302, NULL, NULL, 'Many scientists have warned about the danger of artificial intelligence. Should humans develop more advanced AI? Why?', '许多科学家警告人工智能的危险。人类应该开发更先进的 AI 吗？为什么？', NULL, '可谈收益大于危害并从劳动中解放人类；也可谈可能用于武器，造成科幻电影中的风险。', NULL, 'AI safety, artificial intelligence, discussion', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'review', '复习表达', 5, 'review', 401, NULL, 'Key expressions', 'AI is the most sophisticated and advanced technology field at present. It can help humans in many aspects, such as personal assistants and unmanned vehicles, but it can also be a threat.', '复习：artificial intelligence / sophisticated / advanced / complex / unmanned。', NULL, NULL, NULL, 'review, artificial intelligence', 1),
    ('artificial-intelligence', 'Chapter 13 · Society', 'Lesson 117 · Artificial Intelligence', 117, 'extra', '拓展学习', 6, 'extra', 501, NULL, 'AI', 'Artificial intelligence is becoming more complex and intelligent, from cellphone assistants to vehicle autopilot. Systems more intelligent than humans need safeguards so they only do things people are happy with. Labor-intensive and data-analysis jobs may be replaced by AI.', '人工智能从手机助理到车辆自动驾驶正变得更复杂、更智能。比人类更聪明的系统需要保障措施；劳动密集型和数据分析类工作可能被 AI 替代。', NULL, '课后拓展。', NULL, 'AI, autopilot, jobs', 1)
ON DUPLICATE KEY UPDATE
    `chapter_title` = VALUES(`chapter_title`), `lesson_title` = VALUES(`lesson_title`), `lesson_order` = VALUES(`lesson_order`),
    `section_code` = VALUES(`section_code`), `section_title` = VALUES(`section_title`), `section_order` = VALUES(`section_order`),
    `item_type` = VALUES(`item_type`), `speaker` = VALUES(`speaker`), `item_title` = VALUES(`item_title`),
    `english_text` = VALUES(`english_text`), `chinese_text` = VALUES(`chinese_text`), `pronunciation` = VALUES(`pronunciation`),
    `explanation` = VALUES(`explanation`), `examples` = VALUES(`examples`), `keywords` = VALUES(`keywords`),
    `is_published` = VALUES(`is_published`);

-- Lesson 118 · Sharing Economy (doc/118394_4654_Sharing Economy.pdf)
INSERT INTO `daily_spoken_dialogue_item` (
    `lesson_code`, `chapter_title`, `lesson_title`, `lesson_order`,
    `section_code`, `section_title`, `section_order`, `item_type`, `item_order`,
    `speaker`, `item_title`, `english_text`, `chinese_text`, `pronunciation`,
    `explanation`, `examples`, `keywords`, `is_published`
) VALUES
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'vocabulary', '核心词汇', 1, 'vocabulary', 1, NULL, 'scan the QR code', 'scan the QR code', '扫二维码', NULL, 'to get an image of a pattern of black and white squares containing information, often a web address, that a smartphone camera can read', 'This man is scanning the QR code.', 'scan QR code, sharing economy', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'vocabulary', '核心词汇', 1, 'vocabulary', 2, NULL, 'sharing economy', 'sharing economy', '共享经济', '/ˈʃerɪŋ ɪkɑːnəmi/', 'an economic system in which people share possessions or services, usually by means of the Internet', 'The sharing economy lets people turn a quick profit by renting out rooms, cars, or washing machines.', 'sharing economy', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'vocabulary', '核心词汇', 1, 'vocabulary', 3, NULL, 'thumb a nose at', 'thumb a nose at', '对……嗤之以鼻；蔑视', '/θʌm/', 'to show no respect for someone or something', 'He has thumbed a nose at authority all his life.', 'thumb a nose, sharing economy', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'vocabulary', '核心词汇', 1, 'vocabulary', 4, NULL, 'circulation', 'circulation', '流通', '/ˌsɜːrkjəˈleɪʃn/', 'the passing or spreading of something from one person or place to another', 'There are many sharing cars in circulation.', 'circulation, sharing economy', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'vocabulary', '核心词汇', 1, 'vocabulary', 5, NULL, 'comply with', 'comply with', '服从；遵守；依从', '/kəmˈplaɪ wɪθ/', 'to obey a rule or an order', 'There are serious penalties for failure to comply with the regulations.', 'comply with, regulations', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'dialogue', '示范对话', 2, 'dialogue', 101, 'Jack', NULL, 'This morning, I scanned the QR code on a bike to unlock it before riding it all the way to the company. The sharing economy is so convenient.', '今天早上，我扫了一辆共享单车的二维码解锁，骑到了公司。共享经济真方便。', NULL, NULL, NULL, 'scan QR code, sharing economy', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'dialogue', '示范对话', 2, 'dialogue', 102, 'Mary', NULL, 'At first, lots of people thumbed a nose at this thing. Few people correctly predicted its current popularity.', '一开始，很多人对这件事嗤之以鼻。很少有人正确预测到它现在的流行程度。', NULL, NULL, NULL, 'thumb a nose, popularity', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'dialogue', '示范对话', 2, 'dialogue', 103, 'Jack', NULL, 'Now, there are millions of bikes in circulation. In addition, there are sharing cars, umbrellas, and high-end massage chairs.', '现在有数百万辆自行车在流通。此外，还有共享汽车、雨伞和高端按摩椅。', NULL, NULL, NULL, 'circulation, sharing economy', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'dialogue', '示范对话', 2, 'dialogue', 104, 'Mary', NULL, 'The industry is prosperous. The government has issued regulations to make sure it develops in a healthy way. Each company should comply with the regulations.', '这个行业很繁荣。政府已出台规定以确保它健康发展。每家公司都应遵守规定。', NULL, NULL, NULL, 'regulations, comply with', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'dialogue', '示范对话', 2, 'dialogue', 105, 'Jack', NULL, 'I hope the industry will work out and bring more benefits to the citizens.', '我希望这个行业能顺利发展，并给市民带来更多益处。', NULL, NULL, NULL, 'sharing economy, benefits', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'dialogue', '示范对话', 2, 'dialogue', 106, 'Mary', NULL, 'Me too. Sharing is an efficient way to save resources and provide convenience.', '我也是。共享是节约资源并提供便利的高效方式。', NULL, NULL, NULL, 'sharing, save resources', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'practice', '情景补全对话', 3, 'practice', 201, 'A', NULL, 'What do you think about the sharing economy?', '你怎么看共享经济？', NULL, '根据课件提示补全。', NULL, 'sharing economy, practice', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'practice', '情景补全对话', 3, 'practice', 202, 'B', NULL, 'It''s really convenient. You can ride a bike by simply scanning the QR code, and there are many bikes in circulation.', '它真的很方便。只需扫二维码就能骑车，而且有很多自行车在流通。', NULL, NULL, NULL, 'scan QR code, circulation', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'practice', '情景补全对话', 3, 'practice', 203, 'A', NULL, 'However, the sharing economy also brings many problems, such as streets overloaded with sharing bicycles.', '不过，共享经济也带来许多问题，例如一些街道被共享单车塞满。', NULL, NULL, NULL, 'sharing bicycles, problems', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'practice', '情景补全对话', 3, 'practice', 204, 'B', NULL, 'The government has issued regulations for each company to comply with. It will help create a better sharing economy.', '政府已发布各公司应遵守的规定，这有助于创造更好的共享经济。', NULL, NULL, NULL, 'comply with, regulations', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'discussion', '开口讨论', 4, 'discussion', 301, NULL, NULL, 'Explain sharing economy in your own words. Name sharing services you have used or heard of, and how much they charge for one-time use.', '用自己的话解释共享经济。列举你使用过或听说过的共享服务，以及它们单次使用的费用。', NULL, '可谈共享单车、汽车、玩具、游戏、房间和手机。', NULL, 'sharing economy, discussion', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'discussion', '开口讨论', 4, 'discussion', 302, NULL, NULL, 'What are the advantages and disadvantages of the sharing economy? What should be done to make it better?', '共享经济有哪些优点和缺点？应当做什么来改善它？', NULL, '优点：节约资源、方便、省去购买新品的费用、环保。缺点：服务或商品质量低、市场混乱、企业破产后押金损失。可加强监管、提高质量和消费者权益。', NULL, 'sharing economy, regulation, discussion', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'review', '复习表达', 5, 'review', 401, NULL, 'Key expressions', 'At first, lots of people thumbed a nose at this thing. The government has issued regulations to make sure the industry develops in a healthy way. Each company should comply with the regulations.', '复习：scan the QR code / sharing economy / thumb a nose at / circulation / comply with。', NULL, NULL, NULL, 'review, sharing economy', 1),
    ('sharing-economy', 'Chapter 13 · Society', 'Lesson 118 · Sharing Economy', 118, 'extra', '拓展学习', 6, 'extra', 501, NULL, 'Sharing Nanny', 'Nanny-sharing arrangements let one nanny care for children from two families regularly. They can make childcare more affordable for families and improve nannies'' economic fortunes.', '“共享保姆”安排让一名保姆定期照看两个家庭的孩子，可使家庭更能负担托育，也能改善保姆的经济收入。', NULL, '课后拓展。', NULL, 'nanny sharing, sharing economy, childcare', 1)
ON DUPLICATE KEY UPDATE
    `chapter_title` = VALUES(`chapter_title`), `lesson_title` = VALUES(`lesson_title`), `lesson_order` = VALUES(`lesson_order`),
    `section_code` = VALUES(`section_code`), `section_title` = VALUES(`section_title`), `section_order` = VALUES(`section_order`),
    `item_type` = VALUES(`item_type`), `speaker` = VALUES(`speaker`), `item_title` = VALUES(`item_title`),
    `english_text` = VALUES(`english_text`), `chinese_text` = VALUES(`chinese_text`), `pronunciation` = VALUES(`pronunciation`),
    `explanation` = VALUES(`explanation`), `examples` = VALUES(`examples`), `keywords` = VALUES(`keywords`),
    `is_published` = VALUES(`is_published`);

-- Lesson 115 · Social Security (doc/118391_4654_Social Security.pdf)
INSERT INTO `daily_spoken_dialogue_item` (
    `lesson_code`, `chapter_title`, `lesson_title`, `lesson_order`,
    `section_code`, `section_title`, `section_order`, `item_type`, `item_order`,
    `speaker`, `item_title`, `english_text`, `chinese_text`, `pronunciation`,
    `explanation`, `examples`, `keywords`, `is_published`
) VALUES
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'vocabulary', '核心词汇', 1, 'vocabulary', 1, NULL, 'social security', 'social security', '社会保障；社保', '/ˌsoʊʃl sɪˈkjʊrəti/', 'a system in which people regularly pay the government while working and receive payments when unable to work, especially when sick or old', 'He''s on social security.', 'social security', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'vocabulary', '核心词汇', 1, 'vocabulary', 2, NULL, 'put away', 'put away', '存钱', '/pʊt əˈweɪ/', 'to save money to spend later', 'She puts away many coins.', 'put away, savings', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'vocabulary', '核心词汇', 1, 'vocabulary', 3, NULL, 'retirement', 'retirement', '退休', '/rɪˈtaɪərmənt/', 'the fact of stopping work because you have reached a particular age', 'The old couple go traveling after retirement.', 'retirement, social security', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'vocabulary', '核心词汇', 1, 'vocabulary', 4, NULL, 'deduct', 'deduct', '减去；扣除', '/dɪˈdʌkt/', 'to take away money, points, or other amounts from a total', 'Tax is deducted at source.', 'deduct, salary', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'vocabulary', '核心词汇', 1, 'vocabulary', 5, NULL, 'nest egg', 'nest egg', '备用的钱；储备金', '/ˈnest eɡ/', 'a sum of money that you save to use in the future', 'Over the years she built up a nice little nest egg for her retirement.', 'nest egg, retirement', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'dialogue', '示范对话', 2, 'dialogue', 101, 'Jack', NULL, 'Well, that was an interesting film!', '嗯，那是一部有趣的电影！', NULL, NULL, NULL, 'film, conversation', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'dialogue', '示范对话', 2, 'dialogue', 102, 'Mary', NULL, 'For sure! I didn''t really understand some of the expressions they used in the film when they talked about social security in the US.', '当然！电影谈到美国社保时用的一些表达我不太明白。', NULL, NULL, NULL, 'social security, US', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'dialogue', '示范对话', 2, 'dialogue', 103, 'Mary', NULL, 'They mentioned how people put away money in something called 401k.', '他们提到人们把钱存进一种叫作 401k 的东西。', NULL, NULL, NULL, 'put away, 401k', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'dialogue', '示范对话', 2, 'dialogue', 104, 'Jack', NULL, '401k is a type of retirement plan that allows employees to save and invest for retirement. Although money is deducted from paychecks, people can contribute part of their salary and rest peacefully on their nest egg after retirement.', '401k 是一种让员工为退休储蓄和投资的退休计划。虽然工资单会扣款，人们可以缴纳部分工资，并在退休后安享储备金。', NULL, NULL, NULL, '401k, retirement, deduct, nest egg', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'dialogue', '示范对话', 2, 'dialogue', 105, 'Mary', NULL, 'Sounds like a logical plan to me.', '在我看来这是个合乎逻辑的计划。', NULL, NULL, NULL, 'retirement plan', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'practice', '情景补全对话', 3, 'practice', 201, 'A', NULL, 'Do you put away some money for retirement?', '你会为退休存一些钱吗？', NULL, '根据课件提示补全。', NULL, 'put away, retirement', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'practice', '情景补全对话', 3, 'practice', 202, 'B', NULL, 'Of course, I want to have a peaceful life after retirement.', '当然，我希望退休后过上安稳的生活。', NULL, NULL, NULL, 'retirement', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'practice', '情景补全对话', 3, 'practice', 203, 'A', NULL, 'To be honest, I don''t believe in social security very much. I like to save money in my own accounts.', '说实话，我不太相信社保。我喜欢把钱存到自己的账户里。', NULL, NULL, NULL, 'social security, savings', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'practice', '情景补全对话', 3, 'practice', 204, 'B', NULL, 'That could be an option, but you have to make sure that you build up your nest egg and won''t spend it.', '这也可以，但你必须确保积累起储备金并且不会花掉它。', NULL, NULL, NULL, 'nest egg, savings', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'discussion', '开口讨论', 4, 'discussion', 301, NULL, NULL, 'What does social security mean to you? Talk about social security in China, then ask your teacher about it in his or her country or region.', '社保对你意味着什么？谈谈中国的社保，再询问老师所在国家或地区的情况。', NULL, '可谈退休计划、为将来存钱和储备金。', NULL, 'social security, discussion', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'discussion', '开口讨论', 4, 'discussion', 302, NULL, NULL, 'Do you or your parents put away money for social security? List its advantages and disadvantages.', '你或你的父母会为社保存钱吗？列举它的优点和缺点。', NULL, '优点：退休后有储备金、政府额外缴存、医疗福利。缺点：需长期缴纳大额资金、退休前不可使用、工资扣除后可支配收入较少。', NULL, 'social security, retirement, discussion', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'review', '复习表达', 5, 'review', 401, NULL, 'Key expressions', 'People put away money in something called a 401k. A 401k is a retirement plan that allows employees to save and invest for their own retirement.', '复习：social security / put away / retirement / deduct / nest egg。', NULL, NULL, NULL, 'review, social security', 1),
    ('social-security', 'Chapter 13 · Society', 'Lesson 115 · Social Security', 115, 'extra', '拓展学习', 6, 'extra', 501, NULL, 'Delaying the Retirement Age', 'Some countries have extended the retirement age to adapt to demographic changes and a growing aging population. A policy change requires cautious consideration.', '一些国家为适应人口变化和不断增长的老龄人口而延迟退休年龄；政策调整需要审慎考虑。', NULL, '课后拓展。', NULL, 'retirement age, demographic change', 1)
ON DUPLICATE KEY UPDATE
    `chapter_title` = VALUES(`chapter_title`), `lesson_title` = VALUES(`lesson_title`), `lesson_order` = VALUES(`lesson_order`),
    `section_code` = VALUES(`section_code`), `section_title` = VALUES(`section_title`), `section_order` = VALUES(`section_order`),
    `item_type` = VALUES(`item_type`), `speaker` = VALUES(`speaker`), `item_title` = VALUES(`item_title`),
    `english_text` = VALUES(`english_text`), `chinese_text` = VALUES(`chinese_text`), `pronunciation` = VALUES(`pronunciation`),
    `explanation` = VALUES(`explanation`), `examples` = VALUES(`examples`), `keywords` = VALUES(`keywords`),
    `is_published` = VALUES(`is_published`);

-- Lesson 116 · Aging Population (doc/118392_4654_Aging Population.pdf)
INSERT INTO `daily_spoken_dialogue_item` (
    `lesson_code`, `chapter_title`, `lesson_title`, `lesson_order`,
    `section_code`, `section_title`, `section_order`, `item_type`, `item_order`,
    `speaker`, `item_title`, `english_text`, `chinese_text`, `pronunciation`,
    `explanation`, `examples`, `keywords`, `is_published`
) VALUES
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'vocabulary', '核心词汇', 1, 'vocabulary', 1, NULL, 'proportion', 'proportion', '比率；比例', '/prəˈpɔːrʃn/', 'a part or share of a whole', 'Water covers a large proportion of the earth''s surface.', 'proportion, aging population', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'vocabulary', '核心词汇', 1, 'vocabulary', 2, NULL, 'fertility', 'fertility', '生殖力', '/fərˈtɪləti/', 'the quality of being able to produce young or fruit', 'The fertility rate is declining.', 'fertility, aging population', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'vocabulary', '核心词汇', 1, 'vocabulary', 3, NULL, 'longevity', 'longevity', '长寿', '/lɔːnˈdʒevəti/', 'long life; the fact of lasting a long time', 'We wish you both health and longevity.', 'longevity, aging population', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'vocabulary', '核心词汇', 1, 'vocabulary', 4, NULL, 'adequate', 'adequate', '足够的；合格的', '/ˈædɪkwət/', 'enough in quantity, or good enough in quality, for a particular purpose or need', 'The room was small but adequate.', 'adequate, aging population', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'vocabulary', '核心词汇', 1, 'vocabulary', 5, NULL, 'demographic', 'demographic', '人口的', '/ˌdeməˈɡræfɪk/', 'relating to the population and different groups within it', 'There have been demographic changes.', 'demographic, aging population', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'dialogue', '示范对话', 2, 'dialogue', 101, 'Jack', NULL, 'Do you realize that there are a large proportion of old people in our population structure?', '你意识到我们的人口结构中老年人占很大比例吗？', NULL, NULL, NULL, 'proportion, population structure', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'dialogue', '示范对话', 2, 'dialogue', 102, 'Mary', NULL, 'Yes, the situation of aging population in our country is already pretty serious.', '是的，我国人口老龄化的情况已经相当严重。', NULL, NULL, NULL, 'aging population', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'dialogue', '示范对话', 2, 'dialogue', 103, 'Jack', NULL, 'Why do you think this problem occurred?', '你认为为什么会出现这个问题？', NULL, NULL, NULL, 'aging population', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'dialogue', '示范对话', 2, 'dialogue', 104, 'Mary', NULL, 'In my opinion, it''s mainly because the current population has a lower fertility rate and longer longevity.', '我认为主要是因为当前人口的生育率更低、寿命更长。', NULL, NULL, NULL, 'fertility, longevity', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'dialogue', '示范对话', 2, 'dialogue', 105, 'Jack', NULL, 'That''s right. That''s why our country now allows a couple to give birth to two children.', '没错。这就是为什么我国现在允许一对夫妻生育两个孩子。', NULL, NULL, NULL, 'fertility, population policy', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'dialogue', '示范对话', 2, 'dialogue', 106, 'Mary', NULL, 'The government needs to build a better social security system to provide adequate care for the elder. Only by carrying out effective measures can the country continue to prosper.', '政府需要建立更好的社会保障体系，为老年人提供充分照顾。只有采取有效措施，国家才能持续繁荣。', NULL, NULL, NULL, 'adequate care, social security', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'practice', '情景补全对话', 3, 'practice', 201, 'A', NULL, 'Do you think our economy will continue to prosper?', '你认为我们的经济会继续繁荣吗？', NULL, '根据课件提示补全。', NULL, 'economy, aging population', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'practice', '情景补全对话', 3, 'practice', 202, 'B', NULL, 'It''s hard to say. Our country is facing a serious aging population problem. There are a large proportion of old people in our population structure.', '很难说。我国正面临严重的人口老龄化问题，人口结构中老年人占很大比例。', NULL, NULL, NULL, 'proportion, aging population', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'practice', '情景补全对话', 3, 'practice', 203, 'A', NULL, 'That''s true. I think it''s mainly because people now have a lower fertility rate and longer longevity.', '确实如此。我想主要是因为现在人们的生育率更低、寿命更长。', NULL, NULL, NULL, 'fertility, longevity', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'practice', '情景补全对话', 3, 'practice', 204, 'B', NULL, 'The government needs to figure out a way to deal with this demographic change.', '政府需要想办法应对这种人口变化。', NULL, NULL, NULL, 'demographic change', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'discussion', '开口讨论', 4, 'discussion', 301, NULL, NULL, 'Do you think China is facing a serious aging-population problem? Why did it appear?', '你认为中国正面临严重的人口老龄化问题吗？为什么会出现？', NULL, '可谈较低生育率、较长寿命和过去的计划生育政策。', NULL, 'aging population, discussion', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'discussion', '开口讨论', 4, 'discussion', 302, NULL, NULL, 'Name disadvantages caused by an aging population. What measures could deal with the problem?', '列举人口老龄化造成的弊端。可以采取什么措施来解决？', NULL, '可谈劳动力不足、照护老人的福利或财政负担；可鼓励家庭多生育并建设更好的社会福利和保障体系。', NULL, 'aging population, social welfare, discussion', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'review', '复习表达', 5, 'review', 401, NULL, 'Key expressions', 'It''s mainly because the population has a lower fertility rate and longer longevity. The government has acknowledged the potential crisis of demographic change.', '复习：proportion / fertility / longevity / adequate / demographic。', NULL, NULL, NULL, 'review, aging population', 1),
    ('aging-population', 'Chapter 13 · Society', 'Lesson 116 · Aging Population', 116, 'extra', '拓展学习', 6, 'extra', 501, NULL, 'The Aging Population Affects Economy', 'As more people retire, fewer working-age people replace them. Aging can reduce labor supply and household savings, lowering investment and slowing economic growth.', '随着更多人退休，替代他们的劳动年龄人口减少。老龄化会减少劳动力供给和家庭储蓄，降低投资并拖慢经济增长。', NULL, '课后拓展。', NULL, 'aging population, economy, labor supply', 1)
ON DUPLICATE KEY UPDATE
    `chapter_title` = VALUES(`chapter_title`), `lesson_title` = VALUES(`lesson_title`), `lesson_order` = VALUES(`lesson_order`),
    `section_code` = VALUES(`section_code`), `section_title` = VALUES(`section_title`), `section_order` = VALUES(`section_order`),
    `item_type` = VALUES(`item_type`), `speaker` = VALUES(`speaker`), `item_title` = VALUES(`item_title`),
    `english_text` = VALUES(`english_text`), `chinese_text` = VALUES(`chinese_text`), `pronunciation` = VALUES(`pronunciation`),
    `explanation` = VALUES(`explanation`), `examples` = VALUES(`examples`), `keywords` = VALUES(`keywords`),
    `is_published` = VALUES(`is_published`);

-- Lesson 111 · Green Living (doc/118176_4653_Green Living.pdf)
INSERT INTO `daily_spoken_dialogue_item` (
    `lesson_code`, `chapter_title`, `lesson_title`, `lesson_order`,
    `section_code`, `section_title`, `section_order`, `item_type`, `item_order`,
    `speaker`, `item_title`, `english_text`, `chinese_text`, `pronunciation`,
    `explanation`, `examples`, `keywords`, `is_published`
) VALUES
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'vocabulary', '核心词汇', 1, 'vocabulary', 1, NULL, 'devastation', 'devastation', '毁灭', '/ˌdevəˈsteɪʃn/', 'great destruction or damage, especially over a wide area', 'The bomb caused widespread devastation.', 'devastation, green living', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'vocabulary', '核心词汇', 1, 'vocabulary', 2, NULL, 'green living', 'green living', '绿色生活', '/ɡriːn ˈlɪvɪŋ/', 'attempts to reduce an individual''s or society''s use of the earth''s natural resources and personal resources', 'The belief that green living is expensive is not right.', 'green living, environment', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'vocabulary', '核心词汇', 1, 'vocabulary', 3, NULL, 'unleaded gas', 'unleaded gas', '无铅汽油', '/ˌʌnˈledɪd ɡæs/', 'gas or petrol that does not contain lead and is less harmful to the environment', 'Unleaded gas is cheaper than diesel.', 'unleaded gas, environment', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'vocabulary', '核心词汇', 1, 'vocabulary', 4, NULL, 'renewable energy', 'renewable energy', '可再生能源', '/rɪˈnuːəbl ˈenərdʒi/', 'energy that is naturally replaced or carefully controlled and can be used without the risk of running out', 'We can use renewable energy such as solar energy.', 'renewable energy, environment', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'vocabulary', '核心词汇', 1, 'vocabulary', 5, NULL, 'devoid', 'devoid', '缺乏的', '/dɪˈvɔɪd/', 'completely lacking in something', 'The land is almost devoid of vegetation.', 'devoid, environment', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'dialogue', '示范对话', 2, 'dialogue', 101, 'Jack', NULL, 'Do you think there''s anything we can do to reverse the damage that''s been done to the environment already?', '你觉得我们还能做些什么来扭转已经对环境造成的损害吗？', NULL, NULL, NULL, 'environmental damage', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'dialogue', '示范对话', 2, 'dialogue', 102, 'Mary', NULL, 'It might not be possible to fix the problems that we''ve created for ourselves, but there are lots of things we can do to prevent more devastation from happening.', '也许无法修复我们自己造成的问题，但仍有许多事可以做来防止更多破坏发生。', NULL, NULL, NULL, 'devastation, environment', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'dialogue', '示范对话', 2, 'dialogue', 103, 'Jack', NULL, 'Like what?', '比如什么？', NULL, NULL, NULL, 'conversation', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'dialogue', '示范对话', 2, 'dialogue', 104, 'Mary', NULL, 'Well, we can adopt the green living lifestyle.', '我们可以采用绿色生活方式。', NULL, NULL, NULL, 'green living', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'dialogue', '示范对话', 2, 'dialogue', 105, 'Jack', NULL, 'What is it?', '那是什么？', NULL, NULL, NULL, 'green living', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'dialogue', '示范对话', 2, 'dialogue', 106, 'Mary', NULL, 'For example, you should make sure that your car runs on unleaded gas. If possible, you should use renewable energy at home. The issue of greatest concern is that the Earth may become devoid of clean water for everyone.', '例如，你应确保汽车使用无铅汽油；如果可能，应在家使用可再生能源。最令人担忧的是地球可能缺少供所有人使用的清洁水。', NULL, NULL, NULL, 'unleaded gas, renewable energy, devoid', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'practice', '情景补全对话', 3, 'practice', 201, 'A', NULL, 'Recently, I''ve adopted the green living lifestyle.', '最近我采用了绿色生活方式。', NULL, '根据课件提示补全。', NULL, 'green living, practice', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'practice', '情景补全对话', 3, 'practice', 202, 'B', NULL, 'Green living? What is it?', '绿色生活？那是什么？', NULL, NULL, NULL, 'green living, practice', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'practice', '情景补全对话', 3, 'practice', 203, 'A', NULL, 'For example, you should use cars that run on unleaded gas. You can also use renewable energy at home.', '例如，你应该使用以无铅汽油为燃料的汽车，也可以在家使用可再生能源。', NULL, NULL, NULL, 'unleaded gas, renewable energy', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'practice', '情景补全对话', 3, 'practice', 204, 'B', NULL, 'That sounds like a good idea.', '听起来是个好主意。', NULL, NULL, NULL, 'green living, practice', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'practice', '情景补全对话', 3, 'practice', 205, 'A', NULL, 'If everyone can adopt the green living lifestyle, it can prevent more devastation to the earth from happening.', '如果每个人都能采用绿色生活方式，就能防止地球遭受更多破坏。', NULL, NULL, NULL, 'devastation, green living', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'discussion', '开口讨论', 4, 'discussion', 301, NULL, NULL, 'Explain green living in your own words. What can you do to adopt this lifestyle?', '用自己的话解释“绿色生活”。你能做什么来采用这种生活方式？', NULL, '可谈可持续生活、关心环境；自带购物袋、多乘公共交通、使用无铅汽油和可再生能源、离开时关灯。', NULL, 'green living, discussion', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'discussion', '开口讨论', 4, 'discussion', 302, NULL, NULL, 'From a green-living perspective, what do you think of express delivery and take-outs? What can be done if the situation is harmful?', '从绿色生活的角度看，你如何看待快递和外卖？如果有害，可以做什么？', NULL, '可谈包装会成为垃圾、浪费材料；可使用可回收材料并宣传绿色生活和环境保护。', NULL, 'express delivery, take-outs, green living', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'review', '复习表达', 5, 'review', 401, NULL, 'Key expressions', 'We can do lots of things to prevent more devastation. Make sure your car runs on unleaded gas. If possible, use renewable energy at home. The world may become devoid of clean water for everyone.', '复习：devastation / green living / unleaded gas / renewable energy / devoid。', NULL, NULL, NULL, 'review, green living', 1),
    ('green-living', 'Chapter 12 · Environment', 'Lesson 111 · Green Living', 111, 'extra', '拓展学习', 6, 'extra', 501, NULL, 'The Green Living Lifestyle', 'resource conservation and pollution reduction; green consumption and green purchase; repeated use; recycling; natural protection and co-existence', '绿色生活：节约资源、减少污染；绿色消费和环保选购；重复使用；分类回收；保护自然、万物共存。', NULL, '课后拓展。', NULL, 'green living, recycling, conservation', 1)
ON DUPLICATE KEY UPDATE
    `chapter_title` = VALUES(`chapter_title`), `lesson_title` = VALUES(`lesson_title`), `lesson_order` = VALUES(`lesson_order`),
    `section_code` = VALUES(`section_code`), `section_title` = VALUES(`section_title`), `section_order` = VALUES(`section_order`),
    `item_type` = VALUES(`item_type`), `speaker` = VALUES(`speaker`), `item_title` = VALUES(`item_title`),
    `english_text` = VALUES(`english_text`), `chinese_text` = VALUES(`chinese_text`), `pronunciation` = VALUES(`pronunciation`),
    `explanation` = VALUES(`explanation`), `examples` = VALUES(`examples`), `keywords` = VALUES(`keywords`),
    `is_published` = VALUES(`is_published`);

-- Lesson 114 · Food Safety (doc/118390_4654_Food Safety.pdf)
INSERT INTO `daily_spoken_dialogue_item` (
    `lesson_code`, `chapter_title`, `lesson_title`, `lesson_order`,
    `section_code`, `section_title`, `section_order`, `item_type`, `item_order`,
    `speaker`, `item_title`, `english_text`, `chinese_text`, `pronunciation`,
    `explanation`, `examples`, `keywords`, `is_published`
) VALUES
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'vocabulary', '核心词汇', 1, 'vocabulary', 1, NULL, 'scandal', 'scandal', '丑闻', '/ˈskændl/', 'behavior or an event that people think is morally or legally wrong and that causes shock or anger', 'The media is reporting on his scandal.', 'scandal, food safety', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'vocabulary', '核心词汇', 1, 'vocabulary', 2, NULL, 'expose', 'expose', '使曝光', '/ɪkˈspoʊz/', 'to show something that is usually hidden', 'My job as a journalist is to expose the truth.', 'expose, food safety', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'vocabulary', '核心词汇', 1, 'vocabulary', 3, NULL, 'supervision', 'supervision', '监督；管理', '/ˌsuːpərˈvɪʒn/', 'the activity of being in charge of somebody or something and making sure it is done correctly and safely', 'The old man''s will was executed under the personal supervision of the lawyer.', 'supervision, food safety', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'vocabulary', '核心词汇', 1, 'vocabulary', 4, NULL, 'expired', 'expired', '过期的', '/ɪkˈspaɪərd/', 'no longer valid because the period for which it could be used has ended', 'It''s illegal to sell expired food.', 'expired, food safety', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'vocabulary', '核心词汇', 1, 'vocabulary', 5, NULL, 'additive', 'additive', '添加剂', '/ˈædətɪv/', 'a substance added in small amounts to food to improve it, add color, or make it last longer', 'The juice adds no additives.', 'additive, food safety', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'dialogue', '示范对话', 2, 'dialogue', 101, 'Jack', NULL, 'Do you know that the General Office of the State Council has adopted a stricter standard about food safety?', '你知道国务院办公厅已采用更严格的食品安全标准吗？', NULL, NULL, NULL, 'food safety, standard', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'dialogue', '示范对话', 2, 'dialogue', 102, 'Mary', NULL, 'Yes, and I think it''s an important step in the right direction. Many food safety scandals have been exposed in recent years.', '知道，我认为这是朝正确方向迈出的重要一步。近年来许多食品安全丑闻被曝光。', NULL, NULL, NULL, 'scandal, expose', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'dialogue', '示范对话', 2, 'dialogue', 103, 'Jack', NULL, 'People and the government should improve their awareness about food safety.', '公众和政府都应提高食品安全意识。', NULL, NULL, NULL, 'food safety, awareness', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'dialogue', '示范对话', 2, 'dialogue', 104, 'Mary', NULL, 'Food is the basic need for everyone, so food safety is an important thing in everyone''s interest.', '食品是每个人的基本需要，因此食品安全符合每个人的利益。', NULL, NULL, NULL, 'food safety', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'dialogue', '示范对话', 2, 'dialogue', 105, 'Jack', NULL, 'The new standard will make sure people have safer food, and it will implement better supervision of expired food and additives.', '新标准将确保人们吃到更安全的食品，并对过期食品和添加剂实施更好的监管。', NULL, NULL, NULL, 'supervision, expired, additives', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'dialogue', '示范对话', 2, 'dialogue', 106, 'Mary', NULL, 'I hope we don''t need to worry about food safety anymore.', '我希望我们不必再担心食品安全。', NULL, NULL, NULL, 'food safety', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'dialogue', '示范对话', 2, 'dialogue', 107, 'Jack', NULL, 'I hope so.', '我也希望如此。', NULL, NULL, NULL, 'food safety', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'practice', '情景补全对话', 3, 'practice', 201, 'A', NULL, 'I am so angry. I bought expired food from the supermarket.', '我太生气了。我从超市买到了过期食品。', NULL, '根据课件提示补全。', NULL, 'expired food, practice', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'practice', '情景补全对话', 3, 'practice', 202, 'B', NULL, 'That''s terrible. You should ask for return and refund.', '太糟糕了。你应该要求退货退款。', NULL, NULL, NULL, 'return, refund', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'practice', '情景补全对话', 3, 'practice', 203, 'A', NULL, 'I did, but it still got me worried about food safety.', '我这样做了，但这还是让我担心食品安全。', NULL, NULL, NULL, 'food safety, worry', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'practice', '情景补全对话', 3, 'practice', 204, 'B', NULL, 'You should be. Recently, there are many scandals about food safety that have been exposed.', '你确实该担心。最近许多食品安全丑闻被曝光。', NULL, NULL, NULL, 'scandals, exposed', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'practice', '情景补全对话', 3, 'practice', 205, 'A', NULL, 'Next time I buy something, I will check the date and whether there are harmful additives.', '下次买东西时，我会查看日期以及是否有有害添加剂。', NULL, NULL, NULL, 'additives, food safety', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'discussion', '开口讨论', 4, 'discussion', 301, NULL, NULL, 'Have you ever bought expired food? How did you deal with it? If not, imagine what you would do.', '你买过过期食品吗？你如何处理？如果没有，请设想你会怎么做。', NULL, '可谈要求退货退款、扔掉，以及不再在那家店购买。', NULL, 'expired food, discussion', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'discussion', '开口讨论', 4, 'discussion', 302, NULL, NULL, 'What do you think of the food-safety situation in China? Why? Ask your teacher about the situation in his or her country.', '你如何看待中国的食品安全状况？为什么？也询问老师所在国家的情况。', NULL, '可谈政府正努力确保安全；也可谈努力尚不够、公众仍担忧，政府应更重视。', NULL, 'food safety, discussion', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'review', '复习表达', 5, 'review', 401, NULL, 'Key expressions', 'Many food safety scandals have been exposed in recent years. The new standard will make sure people have safer food and implement better supervision of expired food and additives.', '复习：scandal / expose / supervision / expired / additive。', NULL, NULL, NULL, 'review, food safety', 1),
    ('food-safety', 'Chapter 13 · Society', 'Lesson 114 · Food Safety', 114, 'extra', '拓展学习', 6, 'extra', 501, NULL, 'Some Expressions about Food Safety', 'manufacturing date; expiration date; preservative; stale', '食品安全相关表达：生产日期；保质期／过期日期；防腐剂；不新鲜的。', NULL, '课后拓展词汇。', NULL, 'manufacturing date, expiration date, preservative, stale', 1)
ON DUPLICATE KEY UPDATE
    `chapter_title` = VALUES(`chapter_title`), `lesson_title` = VALUES(`lesson_title`), `lesson_order` = VALUES(`lesson_order`),
    `section_code` = VALUES(`section_code`), `section_title` = VALUES(`section_title`), `section_order` = VALUES(`section_order`),
    `item_type` = VALUES(`item_type`), `speaker` = VALUES(`speaker`), `item_title` = VALUES(`item_title`),
    `english_text` = VALUES(`english_text`), `chinese_text` = VALUES(`chinese_text`), `pronunciation` = VALUES(`pronunciation`),
    `explanation` = VALUES(`explanation`), `examples` = VALUES(`examples`), `keywords` = VALUES(`keywords`),
    `is_published` = VALUES(`is_published`);

-- Lesson 110 · Extinction (doc/118175_4653_Extinction.pdf)
INSERT INTO `daily_spoken_dialogue_item` (
    `lesson_code`, `chapter_title`, `lesson_title`, `lesson_order`,
    `section_code`, `section_title`, `section_order`, `item_type`, `item_order`,
    `speaker`, `item_title`, `english_text`, `chinese_text`, `pronunciation`,
    `explanation`, `examples`, `keywords`, `is_published`
) VALUES
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'vocabulary', '核心词汇', 1, 'vocabulary', 1, NULL, 'extinction', 'extinction', '灭绝', '/ɪkˈstɪŋkʃn/', 'a situation in which a plant, an animal, or a way of life stops existing', 'The extinction of dinosaurs occurred millions of years ago.', 'extinction, environment', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'vocabulary', '核心词汇', 1, 'vocabulary', 2, NULL, 'trafficking', 'trafficking', '非法交易', '/ˈtræfɪkɪŋ/', 'the activity of buying and selling something illegally', 'Animal trafficking is illegal.', 'trafficking, animals', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'vocabulary', '核心词汇', 1, 'vocabulary', 3, NULL, 'conservation', 'conservation', '保护', '/ˌkɑːnsərˈveɪʃn/', 'the protection of the natural environment', 'Pandas happily live in the conservation area.', 'conservation, environment', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'vocabulary', '核心词汇', 1, 'vocabulary', 4, NULL, 'species', 'species', '种；物种', '/ˈspiːʃiːz/', 'a group into which animals or plants able to breed with each other are divided', 'There are many species of cats.', 'species, animals', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'vocabulary', '核心词汇', 1, 'vocabulary', 5, NULL, 'habitat', 'habitat', '栖息地', '/ˈhæbɪtæt/', 'the place where a particular type of animal or plant is normally found', 'The marshes provide a rich habitat for water plants.', 'habitat, environment', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'dialogue', '示范对话', 2, 'dialogue', 101, 'Jack', NULL, 'I''ve been thinking about something lately.', '我最近一直在想一件事。', NULL, NULL, NULL, 'extinction, conversation', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'dialogue', '示范对话', 2, 'dialogue', 102, 'Mary', NULL, 'About what?', '关于什么？', NULL, NULL, NULL, 'conversation', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'dialogue', '示范对话', 2, 'dialogue', 103, 'Jack', NULL, 'How can I help stop the extinction of creatures?', '我怎样才能帮助阻止生物灭绝？', NULL, NULL, NULL, 'stop extinction, creatures', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'dialogue', '示范对话', 2, 'dialogue', 104, 'Mary', NULL, 'Well, we are not the government, but there are some things that we can do to make a difference.', '我们不是政府，但仍有一些事情可以做来产生影响。', NULL, NULL, NULL, 'make a difference, conservation', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'dialogue', '示范对话', 2, 'dialogue', 105, 'Jack', NULL, 'I never buy things made with horns or the fur of animals in danger of extinction. These things mostly come from animal trafficking.', '我从不购买用濒危动物的角或皮毛制成的物品。这些东西大多来自动物非法交易。', NULL, NULL, NULL, 'animal trafficking, extinction', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'dialogue', '示范对话', 2, 'dialogue', 106, 'Mary', NULL, 'That''s a good idea. I tell my friends and people about conservation of species and habitat, just to help spread the idea. If everyone can reduce their negative impact on creatures, we will make a difference.', '这是个好主意。我向朋友和其他人宣传物种与栖息地保护，帮助传播这个理念。如果每个人都减少对生物的不良影响，我们就能有所改变。', NULL, NULL, NULL, 'conservation, species, habitat', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'practice', '情景补全对话', 3, 'practice', 201, 'A', NULL, 'What do you know about animal trafficking?', '你对动物非法交易了解多少？', NULL, '根据课件提示补全。', NULL, 'trafficking, practice', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'practice', '情景补全对话', 3, 'practice', 202, 'B', NULL, 'I know it''s an activity that illegally buys and sells animals that are facing extinction.', '我知道它是非法买卖正面临灭绝的动物的活动。', NULL, NULL, NULL, 'trafficking, extinction', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'practice', '情景补全对话', 3, 'practice', 203, 'A', NULL, 'How can we help to stop it?', '我们如何帮助制止它？', NULL, NULL, NULL, 'stop trafficking', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'practice', '情景补全对话', 3, 'practice', 204, 'B', NULL, 'I talk to my friends and people about conservation of animal species, just to help spread the idea.', '我向朋友和其他人宣传动物物种保护，帮助传播这个理念。', NULL, NULL, NULL, 'conservation, species', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'practice', '情景补全对话', 3, 'practice', 205, 'A', NULL, 'That sounds meaningful.', '这听起来很有意义。', NULL, NULL, NULL, 'conservation, practice', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'discussion', '开口讨论', 4, 'discussion', 301, NULL, NULL, 'Do you know any species that are nearly extinct? Give examples and name reasons why they are nearly extinct.', '你知道哪些濒临灭绝的物种吗？请举例并说明原因。', NULL, '可谈大熊猫、藏羚羊、扬子鳄、中华白海豚；原因包括非法交易、捕猎、栖息地破坏与环境变化。', NULL, 'extinction, species, discussion', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'discussion', '开口讨论', 4, 'discussion', 302, NULL, NULL, 'Is it important to maintain biodiversity for human beings? What can you do to stop animal extinction?', '维护生物多样性对人类重要吗？你能做什么来阻止动物灭绝？', NULL, '可谈稳定环境、研究价值；不买濒危动物的皮毛或角制品，并宣传生物多样性保护。', NULL, 'biodiversity, extinction, discussion', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'review', '复习表达', 5, 'review', 401, NULL, 'Key expressions', 'How can I help stop the extinction of creatures? These things mostly come from trafficking. I tell my friends and people about conservation of species and habitat.', '复习：extinction / trafficking / conservation / species / habitat。', NULL, NULL, NULL, 'review, extinction', 1),
    ('extinction', 'Chapter 12 · Environment', 'Lesson 110 · Extinction', 110, 'extra', '拓展学习', 6, 'extra', 501, NULL, 'Message on World Wildlife Day', 'World Wildlife Day focuses on the important role of wild animals and plants in cultures and sustainable societies. Big cats, including lions and tigers, are increasingly in danger of extinction.', '世界野生动植物日关注野生动植物对文化与社会可持续性的作用；狮子、老虎等大型猫科动物正日益面临灭绝危险。', NULL, '课后拓展：野生动物保护。', NULL, 'World Wildlife Day, big cats, extinction', 1)
ON DUPLICATE KEY UPDATE
    `chapter_title` = VALUES(`chapter_title`), `lesson_title` = VALUES(`lesson_title`), `lesson_order` = VALUES(`lesson_order`),
    `section_code` = VALUES(`section_code`), `section_title` = VALUES(`section_title`), `section_order` = VALUES(`section_order`),
    `item_type` = VALUES(`item_type`), `speaker` = VALUES(`speaker`), `item_title` = VALUES(`item_title`),
    `english_text` = VALUES(`english_text`), `chinese_text` = VALUES(`chinese_text`), `pronunciation` = VALUES(`pronunciation`),
    `explanation` = VALUES(`explanation`), `examples` = VALUES(`examples`), `keywords` = VALUES(`keywords`),
    `is_published` = VALUES(`is_published`);
COMMIT;
