"""Mappings for the existing MySQL schema. Schema changes remain explicit SQL migrations."""

from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)

metadata = MetaData()

english_note = Table(
    "english_note",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("note_date", Date, nullable=False),
    Column("title", String(200), nullable=True),
    Column("source", String(100), nullable=True),
    Column("summary", Text, nullable=True),
    Column("share_status", Integer, nullable=False, server_default=text("'0'")),
    Column("priority_order", Integer, nullable=False, server_default=text("'0'")),
    Column("created_by", Integer, nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_by", Integer, nullable=True),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
)

english_note_item = Table(
    "english_note_item",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("note_id", Integer, nullable=False),
    Column("item_order", Integer, nullable=False, server_default=text("'0'")),
    Column("item_type", String(50), nullable=False, server_default=text("'note_block'")),
    Column("item_title", String(255), nullable=True),
    Column("raw_text", Text, nullable=False),
    Column("english_text", Text, nullable=True),
    Column("chinese_text", Text, nullable=True),
    Column("explanation", Text, nullable=True),
    Column("examples", Text, nullable=True),
    Column("example_image_url", String(500), nullable=True),
    Column("example_image_alt", String(255), nullable=True),
    Column("keywords", String(500), nullable=True),
    Column("share_status", Integer, nullable=False, server_default=text("'0'")),
    Column("priority_order", Integer, nullable=False, server_default=text("'0'")),
    Column("created_by", Integer, nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_by", Integer, nullable=True),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
)

everyday_sentence = Table(
    "everyday_sentence",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("tag", String(100), nullable=False),
    Column("en", Text, nullable=False),
    Column("cn", Text, nullable=False),
    Column("note", Text, nullable=True),
    Column("share_status", Integer, nullable=False, server_default=text("'0'")),
    Column("priority_order", Integer, nullable=False, server_default=text("'0'")),
    Column("created_by", Integer, nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_by", Integer, nullable=True),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
)

interview_answer_section = Table(
    "interview_answer_section",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("question_id", Integer, nullable=False),
    Column("section_type", String(50), nullable=False),
    Column("section_title", String(100), nullable=True),
    Column("content_en", Text, nullable=True),
    Column("content_cn", Text, nullable=True),
    Column("sort_order", Integer, nullable=False, server_default=text("'0'")),
    Column("created_by", Integer, nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_by", Integer, nullable=True),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
)

interview_category = Table(
    "interview_category",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("category_name", String(100), nullable=False),
    Column("category_code", String(50), nullable=False),
    Column("description", String(255), nullable=True),
    Column("sort_order", Integer, nullable=False, server_default=text("'0'")),
    Column("status", Integer, nullable=False, server_default=text("'1'")),
    Column("created_by", Integer, nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_by", Integer, nullable=True),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    UniqueConstraint("category_code"),
)

interview_question = Table(
    "interview_question",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("category_id", Integer, nullable=False),
    Column("question", Text, nullable=False),
    Column("question_cn", Text, nullable=True),
    Column("short_answer", Text, nullable=True),
    Column("full_answer", Text, nullable=True),
    Column("answer_tip", Text, nullable=True),
    Column("keywords", String(500), nullable=True),
    Column("difficulty_level", Integer, nullable=False, server_default=text("'1'")),
    Column("share_status", Integer, nullable=False, server_default=text("'0'")),
    Column("priority_order", Integer, nullable=False, server_default=text("'0'")),
    Column("status", Integer, nullable=False, server_default=text("'1'")),
    Column("created_by", Integer, nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_by", Integer, nullable=True),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
)

interview_question_tag = Table(
    "interview_question_tag",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("question_id", Integer, nullable=False),
    Column("tag_name", String(100), nullable=False),
)

kids_english_card = Table(
    "kids_english_card",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("word", String(100), nullable=False),
    Column("translation", String(255), nullable=False),
    Column("phonics", String(100), nullable=True),
    Column("part_of_speech", String(50), nullable=True),
    Column("level", String(30), nullable=False, server_default=text("'Core'")),
    Column("syllables", String(255), nullable=True),
    Column("stress", String(255), nullable=True),
    Column("phonics_focus", String(255), nullable=True),
    Column("syllable_tip", Text, nullable=True),
    Column("category", String(100), nullable=False),
    Column("emoji", String(32), nullable=True),
    Column("image_url", String(255), nullable=True),
    Column("tip", Text, nullable=True),
    Column("priority_order", Integer, nullable=False, server_default=text("'0'")),
    Column("is_active", Integer, nullable=False, server_default=text("'1'")),
    Column("created_by", Integer, nullable=True),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_by", Integer, nullable=True),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
)

kids_english_card_example = Table(
    "kids_english_card_example",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("card_id", Integer, nullable=False),
    Column("example_text", Text, nullable=False),
    Column("translation", Text, nullable=False),
    Column("priority_order", Integer, nullable=False, server_default=text("'0'")),
    Column("is_active", Integer, nullable=False, server_default=text("'1'")),
)

kids_english_card_sound_part = Table(
    "kids_english_card_sound_part",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("card_id", Integer, nullable=False),
    Column("part_order", Integer, nullable=False),
    Column("chunk", String(100), nullable=False),
    Column("pronunciation", String(100), nullable=False),
    UniqueConstraint("card_id", "part_order"),
)

kids_english_card_word_family = Table(
    "kids_english_card_word_family",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("card_id", Integer, nullable=False),
    Column("related_word", String(100), nullable=False),
    Column("part_of_speech", String(50), nullable=True),
    Column("meaning", String(255), nullable=True),
    Column("priority_order", Integer, nullable=False, server_default=text("'0'")),
)

study_progress = Table(
    "study_progress",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, nullable=False),
    Column("content_type", String(50), nullable=False),
    Column("parent_id", Integer, nullable=True),
    Column("item_id", Integer, nullable=False),
    Column("completed", Integer, nullable=False, server_default=text("'0'")),
    Column("last_studied_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    UniqueConstraint("user_id", "content_type", "parent_id"),
)

user = Table(
    "user",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("username", String(100), nullable=False),
    Column("password_hash", String(255), nullable=False),
    Column("full_name", String(100), nullable=False),
    Column("email", String(150), nullable=True),
    Column("contact_number", String(30), nullable=True),
    Column("home_address", String(255), nullable=True),
    Column("role", String(50), nullable=False, server_default=text("'user'")),
    Column("status", String(50), nullable=False, server_default=text("'active'")),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    UniqueConstraint("username"),
    UniqueConstraint("email"),
)

login_audit = Table(
    "login_audit",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("user.id", ondelete="SET NULL"), nullable=True),
    Column("username", String(100), nullable=False),
    Column("full_name", String(100), nullable=True),
    Column("login_ip", String(45), nullable=True),
    Column("user_agent", String(1000), nullable=True),
    Column("success", Boolean, nullable=False, server_default=text("1")),
    Column("logged_in_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
)
Index("idx_login_audit_logged_in_at", login_audit.c.logged_in_at)
Index("idx_login_audit_user_logged_in_at", login_audit.c.user_id, login_audit.c.logged_in_at)
Index("idx_login_audit_ip_logged_in_at", login_audit.c.login_ip, login_audit.c.logged_in_at)

vocabulary_library = Table(
    "vocabulary_library",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("category", String(100), nullable=False),
    Column("term", String(255), nullable=False),
    Column("chinese_meaning", Text, nullable=True),
    Column("english_note", Text, nullable=True),
    Column("example_sentence", Text, nullable=True),
    Column("extra_note", Text, nullable=True),
    Column("sort_order", Integer, nullable=False, server_default=text("'0'")),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
)

math_card = Table(
    "math_card",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("category", String(100), nullable=False),
    Column("title", String(200), nullable=False),
    Column("summary", Text, nullable=False),
    Column("key_points", Text, nullable=False),
    Column("common_mistakes", Text, nullable=False),
    Column("example_question", Text, nullable=False),
    Column("example_answer", Text, nullable=False),
    Column("example_image_url", String(255), nullable=True),
    Column("sort_order", Integer, nullable=False, server_default=text("0")),
    Column("is_published", Integer, nullable=False, server_default=text("1")),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    UniqueConstraint("title"),
)

english_textbook_lesson = Table(
    "english_textbook_lesson",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("unit_name", String(100), nullable=False),
    Column("lesson_name", String(100), nullable=False),
    Column("title", String(255), nullable=False),
    Column("title_cn", String(255), nullable=True),
    Column("summary", Text, nullable=True),
    Column("unit_order", Integer, nullable=False, server_default=text("0")),
    Column("lesson_order", Integer, nullable=False, server_default=text("0")),
    Column("is_published", Integer, nullable=False, server_default=text("1")),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    UniqueConstraint("unit_name", "lesson_name"),
)

english_textbook_sentence = Table(
    "english_textbook_sentence",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("lesson_id", Integer, nullable=False),
    Column("sentence_order", Integer, nullable=False, server_default=text("0")),
    Column("english_text", Text, nullable=False),
    Column("chinese_text", Text, nullable=False),
    Column("is_published", Integer, nullable=False, server_default=text("1")),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    UniqueConstraint("lesson_id", "sentence_order"),
)

phonics_lesson = Table(
    "phonics_lesson",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("lesson_code", String(80), nullable=False),
    Column("title", String(200), nullable=False),
    Column("subtitle", String(200), nullable=False),
    Column("pattern_text", String(255), nullable=False),
    Column("sound_text", Text, nullable=False),
    Column("learning_tip", Text, nullable=False),
    Column("review_examples_json", Text, nullable=True),
    Column("examples_json", Text, nullable=False),
    Column("quiz_prompt", Text, nullable=False),
    Column("quiz_choices_json", Text, nullable=False),
    Column("quiz_answer", String(255), nullable=False),
    Column("priority_order", Integer, nullable=False, server_default=text("0")),
    Column("is_active", Integer, nullable=False, server_default=text("1")),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    UniqueConstraint("lesson_code"),
)

daily_spoken_dialogue_item = Table(
    "daily_spoken_dialogue_item",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("lesson_code", String(100), nullable=False),
    Column("chapter_title", String(200), nullable=False),
    Column("lesson_title", String(200), nullable=False),
    Column("lesson_order", Integer, nullable=False, server_default=text("0")),
    Column("section_code", String(50), nullable=False),
    Column("section_title", String(200), nullable=False),
    Column("section_order", Integer, nullable=False, server_default=text("0")),
    Column("item_type", String(50), nullable=False),
    Column("item_order", Integer, nullable=False),
    Column("speaker", String(100), nullable=True),
    Column("item_title", String(255), nullable=True),
    Column("english_text", Text, nullable=False),
    Column("chinese_text", Text, nullable=True),
    Column("pronunciation", String(255), nullable=True),
    Column("explanation", Text, nullable=True),
    Column("examples", Text, nullable=True),
    Column("keywords", String(500), nullable=True),
    Column("is_published", Integer, nullable=False, server_default=text("1")),
    Column("created_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")),
    UniqueConstraint("lesson_code", "item_order"),
)
