#!/usr/bin/env python3
"""Apply or export language-register labels for all English note items.

Run the schema migration first:

    mysql happy_english < sql/20260926_classify_english_note_items.sql
    .venv/bin/python scripts/classify_english_note_items.py --apply \
      --write-sql sql/20260926_seed_english_note_item_language_labels.sql

Without ``--apply`` the script only prints the proposed aggregate counts.
Manual labels are preserved unless ``--overwrite`` is supplied.
"""

import argparse
from collections import Counter
import json
from pathlib import Path
import sys

from sqlalchemy import bindparam, select

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app import models as m  # noqa: E402
from app.core.config import Settings  # noqa: E402
from app.core.database import make_engine  # noqa: E402
from app.services.note_language import classify_note_item  # noqa: E402


def classification_values(row):
    classification = classify_note_item(row)
    return {
        "language_register": classification.language_register,
        "usage_scenarios_json": json.dumps(
            classification.usage_scenarios, ensure_ascii=False, separators=(",", ":")
        ),
        "register_reason": classification.register_reason,
        "classification_confidence": classification.classification_confidence,
        "classification_source": classification.classification_source,
    }


def sql_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def write_sql(path: Path, rows):
    """Write a replayable MySQL data migration keyed by stable note-item IDs."""
    values = []
    for row in rows:
        labels = classification_values(row)
        values.append(
            "({})".format(
                ", ".join(
                    sql_literal(value)
                    for value in (
                        row["id"],
                        labels["language_register"],
                        labels["usage_scenarios_json"],
                        labels["register_reason"],
                        labels["classification_confidence"],
                        labels["classification_source"],
                    )
                )
            )
        )

    chunks = [values[index : index + 250] for index in range(0, len(values), 250)]
    lines = [
        "-- Generated by scripts/classify_english_note_items.py.",
        "-- Run after 20260926_classify_english_note_items.sql.",
        "-- Existing manual labels are intentionally preserved.",
        "",
        "DROP TEMPORARY TABLE IF EXISTS `tmp_english_note_item_language_labels`;",
        "CREATE TEMPORARY TABLE `tmp_english_note_item_language_labels` (",
        "    `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,",
        "    `language_register` VARCHAR(32) NOT NULL,",
        "    `usage_scenarios_json` JSON DEFAULT NULL,",
        "    `register_reason` VARCHAR(500) DEFAULT NULL,",
        "    `classification_confidence` TINYINT UNSIGNED DEFAULT NULL,",
        "    `classification_source` VARCHAR(32) NOT NULL",
        ");",
        "",
    ]
    for chunk in chunks:
        lines.extend(
            [
                "INSERT INTO `tmp_english_note_item_language_labels`",
                "(`id`, `language_register`, `usage_scenarios_json`, `register_reason`,",
                " `classification_confidence`, `classification_source`)",
                "VALUES",
                ",\n".join(chunk) + ";",
                "",
            ]
        )
    lines.extend(
        [
            "UPDATE `english_note_item` AS `item`",
            "JOIN `tmp_english_note_item_language_labels` AS `label` ON `label`.`id` = `item`.`id`",
            "SET `item`.`language_register` = `label`.`language_register`,",
            "    `item`.`usage_scenarios_json` = `label`.`usage_scenarios_json`,",
            "    `item`.`register_reason` = `label`.`register_reason`,",
            "    `item`.`classification_confidence` = `label`.`classification_confidence`,",
            "    `item`.`classification_source` = `label`.`classification_source`",
            "WHERE `item`.`classification_source` <> 'manual';",
            "",
            "DROP TEMPORARY TABLE `tmp_english_note_item_language_labels`;",
            "",
            "SELECT `language_register`, COUNT(*) AS `item_count`",
            "FROM `english_note_item`",
            "GROUP BY `language_register`",
            "ORDER BY `item_count` DESC, `language_register`;",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="write labels to the configured database")
    parser.add_argument("--overwrite", action="store_true", help="also replace labels marked manual")
    parser.add_argument("--write-sql", type=Path, help="write a replayable MySQL data migration")
    args = parser.parse_args()

    engine = make_engine(Settings().database_url)
    with engine.connect() as connection:
        rows = connection.execute(select(m.english_note_item).order_by(m.english_note_item.c.id)).mappings().all()
    selected = [
        row
        for row in rows
        if args.overwrite or row.get("classification_source") != "manual"
    ]
    counts = Counter(classification_values(row)["language_register"] for row in selected)
    print(f"Scanned {len(rows)} note items; {len(selected)} eligible for automatic labeling.")
    for language_register, count in sorted(counts.items(), key=lambda entry: (-entry[1], entry[0])):
        print(f"{language_register}: {count}")

    if args.write_sql:
        write_sql(args.write_sql, rows)
        print(f"Wrote {args.write_sql}")

    if not args.apply:
        return

    payloads = []
    for row in selected:
        payloads.append({"_note_item_id": row["id"], **classification_values(row)})
    statement = (
        m.english_note_item.update()
        .where(m.english_note_item.c.id == bindparam("_note_item_id"))
        .values(
            language_register=bindparam("language_register"),
            usage_scenarios_json=bindparam("usage_scenarios_json"),
            register_reason=bindparam("register_reason"),
            classification_confidence=bindparam("classification_confidence"),
            classification_source=bindparam("classification_source"),
        )
    )
    with engine.begin() as connection:
        connection.execute(statement, payloads)
    print(f"Applied automatic labels to {len(payloads)} note items.")


if __name__ == "__main__":
    main()
